name: mobtech
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  http: ^0.12.2
  shared_preferences: ^0.5.8
  provider: ^4.3.2+2
  image_picker: ^0.6.7+2
  firebase_messaging: ^7.0.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/lan.png"


dev_dependencies:
  flutter_launcher_icons: "0.7.3"
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/drawer.jpg
   - images/slider/1.png
   - images/slider/2.png
  #  cat
   - images/category/w.png
   - images/category/sam.jpg
   - images/category/samsung.png
   - images/category/hua.jpg
   - images/category/xia.png
   - images/category/oppo.png
   - images/category/realme.jpg
  # Logo
   - images/logo/samlogo.png
   - images/logo/apple.png
   - images/logo/hua.png
   - images/logo/oppo.png
   - images/logo/xia.png
   - images/logo/realme.jpg
  #  product
   - images/product/1.jpg
   - images/product/2.jpg
   - images/product/3.jpg
   - images/product/4.jpg
  #  flags
   - images/flags/alg.png  
   - images/flags/eg.png  
   - images/flags/jo.png  
   - images/flags/sa.png  
   - images/flags/uae.png  
   - images/flags/sy.png 
 
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo/Cairo-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
